version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_bot
    ports:
      - 5432:5432
    volumes:
      - db:/var/postgresql/data/

volumes:
  db:
